const guideTests = [
  { id: 'HP-01', title: 'View Data in the Table', status: 'safe' },
  { id: 'HP-02', title: 'Select and Deselect Rows', status: 'safe' },
  { id: 'HP-03', title: 'Edit a Text Cell', status: 'partial-safe' },
  { id: 'HP-04', title: 'Edit a Single Select Cell', status: 'controlled' },
  { id: 'HP-05', title: 'Edit a Multi Select Cell', status: 'controlled' },
  { id: 'HP-06', title: 'Edit a Date Cell', status: 'controlled' },
  { id: 'HP-07', title: 'Upload a File (Simple Storage Mode)', status: 'controlled' },
  { id: 'HP-08', title: 'Upload a File (OCR+LLM Advanced Mode)', status: 'controlled' },
  { id: 'HP-09', title: 'Score Cell Color Coding', status: 'controlled' },
  { id: 'HP-10', title: 'Resize a Column', status: 'controlled' },
  { id: 'HP-11', title: 'Resize a Row', status: 'controlled' },
  { id: 'HP-12', title: 'Reorder a Column via Drag', status: 'controlled' },
  { id: 'HP-13', title: 'Reorder a Row via Drag', status: 'controlled' },
  { id: 'HP-14', title: 'Add a New Column', status: 'partial-safe' },
  { id: 'HP-15', title: 'Configure Column Properties', status: 'partial-safe' },
  { id: 'HP-16', title: 'Pin and Unpin a Column', status: 'partial-safe' },
  { id: 'HP-17', title: 'Delete a Column', status: 'controlled' },
  { id: 'HP-18', title: 'Bulk Delete Rows', status: 'controlled' },
  { id: 'HP-19', title: 'Apply a Sort Rule', status: 'partial-safe' },
  { id: 'HP-20', title: 'Apply a Filter Rule', status: 'partial-safe' },
  { id: 'HP-21', title: 'Create and Switch Views', status: 'controlled' },
  { id: 'HP-22', title: 'Modify and Save Changes to an Existing View', status: 'controlled' },
  { id: 'HP-23', title: 'Select/Multiselect Option Management', status: 'controlled' },
  { id: 'HP-24', title: 'AI Prompt Configuration', status: 'controlled' },
  { id: 'EC-01', title: 'Double-Click on Non-Editable Cells', status: 'safe' },
  { id: 'EC-02', title: 'Rapid Double-Clicking Different Cells', status: 'safe' },
  { id: 'EC-03', title: 'Enter Extremely Long Text', status: 'controlled' },
  { id: 'EC-04', title: 'Enter Invalid Data in a Number/Score Cell', status: 'controlled' },
  { id: 'EC-05', title: 'Empty Table (Zero Rows)', status: 'controlled' },
  { id: 'EC-06', title: 'Table with Zero Columns (Template Mode)', status: 'controlled' },
  { id: 'EC-07', title: 'Resize Column to Minimum Width', status: 'controlled' },
  { id: 'EC-08', title: 'Resize Row to Minimum Height', status: 'controlled' },
  { id: 'EC-09', title: 'Create a Duplicate View', status: 'controlled' },
  { id: 'EC-10', title: 'Save View with Empty Name', status: 'controlled' },
  { id: 'EC-11', title: 'Sort by Multiple Columns', status: 'controlled' },
  { id: 'EC-12', title: 'Filter "isEmpty" and "isNotEmpty"', status: 'controlled' },
  { id: 'EC-13', title: 'Click Outside Flyout to Auto-Save', status: 'controlled' },
  { id: 'EC-14', title: 'Scroll Table While Flyout Is Open', status: 'partial-safe' },
  { id: 'EC-15', title: 'File Upload Failure', status: 'controlled' },
  { id: 'EC-16', title: 'Column Property Flyout - No Changes', status: 'safe' },
  { id: 'EC-17', title: 'Assign a Team Member (Assignments Column)', status: 'controlled' },
  { id: 'EC-18', title: 'Email Column Behavior', status: 'controlled' },
  { id: 'EC-19', title: 'Pinned Column + Drag Prevention', status: 'controlled' },
  { id: 'VC-01', title: 'Column Alignment', status: 'safe' },
  { id: 'VC-02', title: 'Horizontal Scroll', status: 'partial-safe' },
  { id: 'VC-03', title: 'Vertical Scroll', status: 'partial-safe' },
  { id: 'VC-04', title: 'Flyout Editor Positioning', status: 'controlled' },
  { id: 'VC-05', title: 'Score Badge Colors', status: 'controlled' },
  { id: 'VC-06', title: 'Select/MultiSelect Tag Colors', status: 'controlled' },
  { id: 'VC-07', title: 'Empty Cell Display', status: 'safe' },
  { id: 'VC-08', title: 'Batch Action Bar vs View Bar', status: 'safe' },
  { id: 'VC-09', title: 'Column Property Flyout Scroll', status: 'controlled' },
  { id: 'VC-10', title: 'Table Font Consistency', status: 'safe' },
  { id: 'AI-01', title: 'Resume Upload -> Auto-Fill Row', status: 'controlled' },
  { id: 'AI-02', title: 'Prompt-Based Skill Extraction Without File Parsing', status: 'controlled' },
  { id: 'AI-03', title: 'AI Candidate Scoring', status: 'controlled' },
  { id: 'AI-04', title: 'Multi-Step Dependency Chain', status: 'controlled' },
  { id: 'AI-05', title: 'Recompute Stale Fields Button', status: 'controlled' },
  { id: 'AI-06', title: 'File Parser Template - Create, Use, and Reuse', status: 'controlled' },
  { id: 'AI-07', title: 'Stage Change Does Not Break Dependencies', status: 'controlled' },
  { id: 'AI-08', title: 'Editing a Computed Cell Manually', status: 'controlled' },
  { id: 'AI-09', title: 'Prompt with No Input Columns Referenced', status: 'controlled' },
  { id: 'AI-10', title: 'Parent Column References (@@)', status: 'controlled' },
  { id: 'AI-11', title: 'Upload a Non-Parseable File', status: 'controlled' },
  { id: 'AI-12', title: 'Rapid Sequential Edits to an Input Column', status: 'controlled' },
];

module.exports = { guideTests };
